TARGET_KERNEL_USE ?= 5.10

KERNEL_MODULES_PATH := kernel-custom/out/android12-$(TARGET_KERNEL_USE)/dist

KERNEL_MODULES_EXCLUDE := \
    $(KERNEL_MODULES_PATH)/virt_wifi.ko \
    $(KERNEL_MODULES_PATH)/virt_wifi_sim.ko

BOARD_VENDOR_RAMDISK_KERNEL_MODULES += \
    $(filter-out $(KERNEL_MODULES_EXCLUDE), $(wildcard $(KERNEL_MODULES_PATH)/*.ko))

EMULATOR_KERNEL_FILE := $(KERNEL_MODULES_PATH)/bzImage
